### PR TITLE
Update core.cpp

### PR DESCRIPTION
**Pull request by lagcompensation**
some minor fixes
btw i think he looks nice

### CODE REVIEW

**Comment by maecry** [comment]
Uhm i don't see the reason of using std::thread except it might help with manual mapping injector, the only good one here is the multiple .dll schema dumps

**Comment by maecry** [comment]
And u also completely void the Destroy()

**Comment by lagcompensation** [comment]
> Uhm i don't see the reason of using std::thread except it might help with manual mapping injector, the only good one here is the multiple .dll schema dumps

but except that the jthread is automatically rejoined when destroyed and can be canceled/stopped in certain situations. it will be better than what was before, at least you can “control” the thread

**Comment by maecry** [comment]
Sry been busy lately, but yea still no reason of using it with other stl stuffs 🤗

**Pull request closed without merging**
