### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by HellishPhobos**
Cursor bug fix and minor change related to the game version update

### CODE REVIEW

**Comment by ogpolak05** [comment]
mouse cursor in game status stolen

**Comment by ogpolak05** [comment]
to avoid stolen mouse cursor here is simple fix `LRESULT CALLBACK WndProc::hkWndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
{
	if (uMsg == WM_KEYDOWN && wParam == VK_INSERT) {
		VarsGui::Open = !VarsGui::Open;
		if (GameInterfaces::g_pInputSystem->IsRelativeMouseMode())
			g_pMemoryExport->fnSetRelativeMouseMode(!VarsGui::Open);
	}

	if (ImGui_ImplWin32_WndProcHandler(hWnd, uMsg, wParam, lParam))
		return true;

	if (VarsGui::Open) {

		switch (uMsg) {
		case WM_MOUSEMOVE:
		case WM_LBUTTONDOWN:
		case WM_LBUTTONUP:
		case WM_RBUTTONDOWN:
		case WM_RBUTTONUP:
		case WM_MBUTTONDOWN:
		case WM_MBUTTONUP:
		case WM_MOUSEWHEEL:
		case WM_XBUTTONDOWN:
		case WM_XBUTTONUP:
			return 0;

		default:
			break;
		}
	}

	return CallWindowProc(WndProc, hWnd, uMsg, wParam, lParam);
}`

**Comment by ogpolak05** [comment]
broken github

**Comment by Exlodium** [comment]
0x40 is the wrong offset for IsRelativeMouseMode. I am guessing you added the IsInGame check to avoid the cursor disapearing in menu when you close the gui.

**Comment by HellishPhobos** [comment]
> 0x40 is the wrong offset for IsRelativeMouseMode. I am guessing you added the IsInGame check to avoid the cursor disapearing in menu when you close the gui.

Just download the "fixes" branch from my fork and check in the game, everything works perfectly as it should

**Comment by ogpolak05** [comment]
@Exlodium you should try mine wndproc in my base I implemented @HellishPhobos fixes and everything works perfectly as it was before goyim update

`extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam);
LRESULT CALLBACK WndProc::hkWndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
{
	if (uMsg == WM_KEYDOWN && wParam == VK_INSERT) {
		VarsGui::Open = !VarsGui::Open;
		if (GameInterfaces::g_pEngine->IsInGame()) {
			if (GameInterfaces::g_pInputSystem->IsRelativeMouseMode())
				g_pMemoryExport->fnSetRelativeMouseMode(!VarsGui::Open);
		}
	}

	if (ImGui_ImplWin32_WndProcHandler(hWnd, uMsg, wParam, lParam) || VarsGui::Open)
		return true;

	if (VarsGui::Open) {

		switch (uMsg) {
		case WM_MOUSEMOVE:
		case WM_LBUTTONDOWN:
		case WM_LBUTTONUP:
		case WM_RBUTTONDOWN:
		case WM_RBUTTONUP:
		case WM_MBUTTONDOWN:
		case WM_MBUTTONUP:
		case WM_MOUSEWHEEL:
		case WM_XBUTTONDOWN:
		case WM_XBUTTONUP:
			return 0;

		default:
			break;
		}
	}

	return CallWindowProc(WndProc, hWnd, uMsg, wParam, lParam);
}`

**Pull request closed without merging**
