### PR TITLE
Add Teamate ESP

### PR DESCRIPTION
**Pull request by t0r-onion**
Sometimes it is nice to see where your teamates are at that's why i decided to add Teamate ESP :)

### CODE REVIEW

**Comment by t0r-onion** [comment]
not a **major** change but could be useful

**Comment by maecry** [comment]
Lol? You don't even check if it's teammates or not, just only check if the var is enabled, ik i merged low quality pr but this is on next level

**Comment by t0r-onion** [comment]
that check legit checks if entity is not equal to teamate if it is it just returns so are you stupid or something?

**Comment by maecry** [comment]
> that check legit checks if entity is not equal to teamate if it is it just returns so are you stupid or something?
> 
> i mean you wrote it how the hell does one not know how his own code works? what i did was add to a simple condition that if the feature is enabled it wont skip teamates. (explained what an if statement means for your **special** kind of brain.)

Screenshot_20240822_074057_Edge
Lil bro.... u only add if the the var is enabled or not, i shouldn't even explain what's wrong

**Comment by maecry** [comment]
> > that check legit checks if entity is not equal to teamate if it is it just returns so are you stupid or something?
> > i mean you wrote it how the hell does one not know how his own code works? what i did was add to a simple condition that if the feature is enabled it wont skip teamates. (explained what an if statement means for your **special** kind of brain.)
> 
> Screenshot_20240822_074057_Edge Lil bro.... u only add if the the var is enabled or not, i shouldn't even explain what's wrong
> 
> If you want to properly add this, take a look at qo0 as this base it heavily inspired from it https://github.com/rollraw/qo0-csgo/blob/590d2132374db3aa43d5ce656f6b3f34950430eb/base/features/visual/overlay.cpp#L560
> 
> Next time learn to code properly instead of being toxic

Also from now on I'll stop merging low quality stuffs to reduce this happen again

**Pull request closed without merging**
